using MaterialDesignThemes.Wpf;
using ReactiveUI;
using ReactiveUI.SourceGenerators;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace YoutubeDl.Wpf.Models;

public partial class ObservableSettings(Settings settings) : ReactiveObject
{
    public Settings AppSettings { get; } = settings;

    [Reactive]
    private BaseTheme _appColorMode = settings.AppColorMode;

    [Reactive]
    private double _windowWidth = settings.WindowWidth;

    [Reactive]
    private double _windowHeight = settings.WindowHeight;

    [Reactive]
    private BackendTypes _backend = settings.Backend;

    [Reactive]
    private string _backendPath = settings.BackendPath;

    /// <summary>
    /// Gets or sets the list of arguments passed
    /// to the backend process for all types of operations.
    /// </summary>
    [Reactive]
    private ObservableCollection<BackendArgument> _backendGlobalArguments = [.. settings.BackendGlobalArguments];

    /// <summary>
    /// Gets or sets the list of arguments passed
    /// to the backend process for download operations.
    /// </summary>
    [Reactive]
    private List<BackendArgument> _backendDownloadArguments = [.. settings.BackendDownloadArguments];

    [Reactive]
    private bool _backendAutoUpdate = settings.BackendAutoUpdate;

    [Reactive]
    private DateTimeOffset _backendLastUpdateCheck = settings.BackendLastUpdateCheck;

    [Reactive]
    private string _ffmpegPath = settings.FfmpegPath;

    [Reactive]
    private string _proxy = settings.Proxy;

    [Reactive]
    private int _loggingMaxEntries = settings.LoggingMaxEntries;

    [Reactive]
    private Preset? _selectedPreset = settings.SelectedPreset;

    /// <summary>
    /// This is a hack to prevent <see cref="SelectedPreset"/> from being changed to null.
    /// Another solution is to manually implement equality for <see cref="Preset"/>,
    /// which is much harder to get it right, and would look terrible compared to this little hack.
    /// </summary>
    [Reactive]
    private string _selectedPresetText = settings.SelectedPreset.DisplayName;

    [Reactive]
    private List<Preset> _customPresets = [.. settings.CustomPresets];

    [Reactive]
    private bool _addMetadata = settings.AddMetadata;

    [Reactive]
    private bool _downloadThumbnail = settings.DownloadThumbnail;

    [Reactive]
    private bool _downloadSubtitles = settings.DownloadSubtitles;

    [Reactive]
    private bool _downloadSubtitlesAllLanguages = settings.DownloadSubtitlesAllLanguages;

    [Reactive]
    private bool _downloadAutoGeneratedSubtitles = settings.DownloadAutoGeneratedSubtitles;

    [Reactive]
    private bool _downloadPlaylist = settings.DownloadPlaylist;

    [Reactive]
    private bool _useCustomOutputTemplate = settings.UseCustomOutputTemplate;

    [Reactive]
    private string _customOutputTemplate = settings.CustomOutputTemplate;

    /// <summary>
    /// Gets the list of used output templates.
    /// New templates are appended to the list.
    /// </summary>
    public List<string> OutputTemplateHistory { get; } = [.. settings.OutputTemplateHistory];

    [Reactive]
    private bool _useCustomPath = settings.UseCustomPath;

    [Reactive]
    private string _downloadPath = settings.DownloadPath;

    /// <summary>
    /// Gets the list of used download paths.
    /// New paths are appended to the list.
    /// </summary>
    public List<string> DownloadPathHistory { get; } = [.. settings.DownloadPathHistory];

    public void UpdateAppSettings()
    {
        AppSettings.AppColorMode = AppColorMode;
        AppSettings.WindowWidth = WindowWidth;
        AppSettings.WindowHeight = WindowHeight;
        AppSettings.Backend = Backend;
        AppSettings.BackendPath = BackendPath;
        AppSettings.BackendGlobalArguments = [.. BackendGlobalArguments];
        AppSettings.BackendDownloadArguments = [.. BackendDownloadArguments];
        AppSettings.BackendAutoUpdate = BackendAutoUpdate;
        AppSettings.BackendLastUpdateCheck = BackendLastUpdateCheck;
        AppSettings.FfmpegPath = FfmpegPath;
        AppSettings.Proxy = Proxy;
        // AppSettings.LoggingMaxEntries is managed by the validation handler.
        AppSettings.SelectedPreset = SelectedPreset ?? Preset.Auto;
        AppSettings.CustomPresets = [.. CustomPresets];
        AppSettings.AddMetadata = AddMetadata;
        AppSettings.DownloadThumbnail = DownloadThumbnail;
        AppSettings.DownloadSubtitles = DownloadSubtitles;
        AppSettings.DownloadSubtitlesAllLanguages = DownloadSubtitlesAllLanguages;
        AppSettings.DownloadAutoGeneratedSubtitles = DownloadAutoGeneratedSubtitles;
        AppSettings.DownloadPlaylist = DownloadPlaylist;
        AppSettings.UseCustomOutputTemplate = UseCustomOutputTemplate;
        AppSettings.CustomOutputTemplate = CustomOutputTemplate;
        AppSettings.UseCustomPath = UseCustomPath;
        AppSettings.OutputTemplateHistory = [.. OutputTemplateHistory];
        AppSettings.DownloadPath = DownloadPath;
        AppSettings.DownloadPathHistory = [.. DownloadPathHistory];
    }
}
