using MaterialDesignThemes.Wpf;
using ReactiveUI;
using ReactiveUI.Fody.Helpers;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Threading;
using System.Threading.Tasks;
using YoutubeDl.Wpf.Utils;

namespace YoutubeDl.Wpf.Models
{
    public class Settings : ReactiveObject
    {
        /// Gets the default configuration version
        /// used by this version of the app.
        /// </summary>
        public static int DefaultVersion => 1;

        /// <summary>
        /// Gets the default custom output filename template.
        /// We use yt-dlp's default as the default custom value.
        /// </summary>
        public static string DefaultCustomFilenameTemplate => "%(title)s [%(id)s].%(ext)s";

        /// <summary>
        /// Gets or sets the settings version number.
        /// Defaults to <see cref="DefaultVersion"/>.
        /// </summary>
        public int Version { get; set; } = DefaultVersion;

        public BaseTheme AppColorMode { get; set; } = BaseTheme.Inherit;

        [Reactive]
        public BackendTypes Backend { get; set; } = BackendTypes.Ytdl;

        [Reactive]
        public string BackendPath { get; set; } = "";

        /// <summary>
        /// Gets or sets the list of arguments passed
        /// to the backend process for all types of operations.
        /// </summary>
        public ObservableCollection<BackendArgument> BackendGlobalArguments { get; set; } = new();

        /// <summary>
        /// Gets or sets the list of arguments passed
        /// to the backend process for download operations.
        /// </summary>
        public List<BackendArgument> BackendDownloadArguments { get; set; } = new();

        [Reactive]
        public bool BackendAutoUpdate { get; set; } = true;

        [Reactive]
        public string FfmpegPath { get; set; } = "";

        [Reactive]
        public string Proxy { get; set; } = "";

        [Reactive]
        public int LoggingMaxEntries { get; set; } = 1024;

        [Reactive]
        public string ContainerText { get; set; } = "Auto";

        [Reactive]
        public Format? SelectedContainer { get; set; } = Format.Auto;

        [Reactive]
        public string FormatText { get; set; } = "Auto";

        [Reactive]
        public Format? SelectedFormat { get; set; } = Format.Auto;

        [Reactive]
        public bool AddMetadata { get; set; } = true;

        [Reactive]
        public bool DownloadThumbnail { get; set; } = true;

        [Reactive]
        public bool DownloadSubtitles { get; set; } = true;

        [Reactive]
        public bool DownloadSubtitlesAllLanguages { get; set; }

        [Reactive]
        public bool DownloadAutoGeneratedSubtitles { get; set; }

        [Reactive]
        public bool DownloadPlaylist { get; set; }

        [Reactive]
        public bool UseCustomOutputTemplate { get; set; }

        [Reactive]
        public string CustomOutputTemplate { get; set; } = DefaultCustomFilenameTemplate;

        [Reactive]
        public bool UseCustomPath { get; set; }

        [Reactive]
        public string DownloadPath { get; set; } = "";

        /// <summary>
        /// Gets the list of download path history.
        /// New paths are always appended to the list.
        /// </summary>
        public List<string> DownloadPathHistory { get; set; } = new();

        /// <summary>
        /// Loads settings from Settings.json.
        /// </summary>
        /// <param name="cancellationToken">A token that may be used to cancel the read operation.</param>
        /// <returns>
        /// A ValueTuple containing a <see cref="Settings"/> object and an optional error message.
        /// </returns>
        public static async Task<(Settings settings, string? errMsg)> LoadSettingsAsync(CancellationToken cancellationToken = default)
        {
            var (settings, errMsg) = await FileHelper.LoadJsonAsync<Settings>("Settings.json", FileHelper.commonJsonDeserializerOptions, cancellationToken).ConfigureAwait(false);
            if (errMsg is null && settings.Version != DefaultVersion)
            {
                settings.UpdateSettings();
                errMsg = await SaveSettingsAsync(settings, cancellationToken).ConfigureAwait(false);
            }
            return (settings, errMsg);
        }

        /// <summary>
        /// Saves settings to Settings.json.
        /// </summary>
        /// <param name="settings">The <see cref="Settings"/> object to save.</param>
        /// <param name="cancellationToken">A token that may be used to cancel the write operation.</param>
        /// <returns>
        /// An optional error message.
        /// Null if no errors occurred.
        /// </returns>
        public static Task<string?> SaveSettingsAsync(Settings settings, CancellationToken cancellationToken = default)
            => FileHelper.SaveJsonAsync("Settings.json", settings, FileHelper.commonJsonSerializerOptions, false, false, cancellationToken);

        /// <summary>
        /// Updates the current object to the latest version.
        /// </summary>
        public void UpdateSettings()
        {
            switch (Version)
            {
                case 0: // nothing to do
                    Version++;
                    goto default; // go to the next update path
                default:
                    break;
            }
        }
    }
}
